import type { AnalysisResult, ClauseAnalysis, RiskLevel } from "@/lib/types";
import { RISK_LEVEL_ORDER } from "@/lib/constants";
import { sanitizePdfText } from "@/lib/sanitize";

// jsPDF is dynamically loaded to avoid SSR issues and keep the bundle lean.
// This module is client-only.

const PAGE_MARGIN = 15;
const PAGE_WIDTH = 210; // A4 mm
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;

type RGB = [number, number, number];

const RISK_COLORS: Record<RiskLevel, RGB> = {
  RED: [192, 57, 43],
  YELLOW: [180, 83, 9],
  CONTEXT_DEPENDENT: [100, 100, 110],
  GREEN: [45, 106, 79],
};

const RISK_LABEL: Record<RiskLevel, string> = {
  RED: "Red Flag",
  YELLOW: "Unusual",
  CONTEXT_DEPENDENT: "Context Dependent",
  GREEN: "Standard",
};

const URGENCY_PREFIX = { HIGH: "[HIGH] ", MEDIUM: "[MED] ", LOW: "[LOW] " } as const;

async function loadJsPDF() {
  const { jsPDF } = await import("jspdf");
  return jsPDF;
}

function addWrappedText(
  doc: InstanceType<Awaited<ReturnType<typeof loadJsPDF>>>,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const lines = doc.splitTextToSize(sanitizePdfText(text), maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function checkPageBreak(
  doc: InstanceType<Awaited<ReturnType<typeof loadJsPDF>>>,
  y: number,
  needed = 20,
): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - PAGE_MARGIN) {
    doc.addPage();
    return PAGE_MARGIN + 5;
  }
  return y;
}

function getNumberOfPages(doc: InstanceType<Awaited<ReturnType<typeof loadJsPDF>>>): number {
  const internal = doc.internal as unknown as Record<string, unknown>;
  if (typeof internal["getNumberOfPages"] !== "function") {
    throw new Error("jsPDF internal API changed: getNumberOfPages not found");
  }
  return (internal["getNumberOfPages"] as () => number)();
}

function addFooter(
  doc: InstanceType<Awaited<ReturnType<typeof loadJsPDF>>>,
  pageNum: number,
  total: number,
) {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum} of ${total}`, PAGE_MARGIN, pageHeight - 8);
  doc.text("Generated by LexLight — not legal advice", PAGE_WIDTH / 2, pageHeight - 8, {
    align: "center",
  });
}

function renderClause(
  doc: InstanceType<Awaited<ReturnType<typeof loadJsPDF>>>,
  clause: ClauseAnalysis,
  y: number,
): number {
  const color = RISK_COLORS[clause.riskLevel];
  const label = RISK_LABEL[clause.riskLevel];

  y = checkPageBreak(doc, y, 30);

  // Risk badge + title
  doc.setFontSize(9);
  doc.setTextColor(...color);
  doc.text(`[${label.toUpperCase()}]`, PAGE_MARGIN, y);
  const badgeWidth = doc.getTextWidth(`[${label.toUpperCase()}] `);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(14, 15, 22);
  const titleLines = doc.splitTextToSize(
    sanitizePdfText(clause.title),
    CONTENT_WIDTH - badgeWidth,
  ) as string[];
  doc.text(titleLines, PAGE_MARGIN + badgeWidth, y);
  y += titleLines.length * 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(14, 15, 22);

  if (clause.affectedByMismatch) {
    y = checkPageBreak(doc, y, 8);
    doc.setTextColor(180, 83, 9);
    doc.text("⚠ Affected by jurisdiction mismatch", PAGE_MARGIN + 2, y);
    doc.setTextColor(14, 15, 22);
    y += 5;
  }

  y = checkPageBreak(doc, y, 10);
  y = addWrappedText(doc, clause.plainEnglish, PAGE_MARGIN + 2, y, CONTENT_WIDTH - 2, 5);
  y += 3;

  doc.setFontSize(9);
  doc.setTextColor(92, 92, 102);

  const fields: Array<[string, string | null | undefined]> = [
    ["Why it matters:", clause.riskReason],
    ["Compared to standard:", clause.comparisonToStandard],
    ["Your obligation:", clause.obligation],
    ["Context note:", clause.contextNote],
    ["Negotiation tip:", clause.negotiationTip],
  ];

  for (const [fieldLabel, value] of fields) {
    if (!value) continue;
    y = checkPageBreak(doc, y, 8);
    doc.setFont("helvetica", "bold");
    doc.text(fieldLabel, PAGE_MARGIN + 2, y);
    const labelW = doc.getTextWidth(fieldLabel + " ");
    doc.setFont("helvetica", "normal");
    y = addWrappedText(doc, value, PAGE_MARGIN + 2 + labelW, y, CONTENT_WIDTH - 2 - labelW, 5);
    y += 2;
  }

  doc.setTextColor(200, 200, 200);
  doc.line(PAGE_MARGIN, y, PAGE_MARGIN + CONTENT_WIDTH, y);
  y += 4;

  return y;
}

export async function toPdf(analysis: AnalysisResult): Promise<Blob> {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const date = new Date(analysis.analyzedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let y = PAGE_MARGIN + 5;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(14, 15, 22);
  doc.text("LexLight Analysis Report", PAGE_MARGIN, y);
  y += 10;

  // Metadata
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(92, 92, 102);
  const meta = [
    `Document type: ${analysis.documentType.replace(/_/g, " ")}`,
    `Governing law: ${analysis.governingLawJurisdiction ?? "Not specified"}`,
    `Effective jurisdiction: ${analysis.effectiveJurisdiction}`,
    `Overall risk: ${analysis.overallRiskLabel} (${analysis.overallRiskScore}/100)`,
    `Analyzed: ${date}`,
  ];
  for (const line of meta) {
    doc.text(line, PAGE_MARGIN, y);
    y += 5;
  }
  y += 3;

  doc.setDrawColor(230, 220, 205);
  doc.line(PAGE_MARGIN, y, PAGE_MARGIN + CONTENT_WIDTH, y);
  y += 6;

  // Jurisdiction mismatch
  if (analysis.jurisdictionMismatch) {
    const m = analysis.jurisdictionMismatch;
    y = checkPageBreak(doc, y, 30);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(180, 83, 9);
    doc.text(`⚠ Jurisdiction Mismatch (${m.confidence} confidence)`, PAGE_MARGIN, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(14, 15, 22);
    y = addWrappedText(doc, m.plainEnglish, PAGE_MARGIN, y, CONTENT_WIDTH, 5);
    y += 3;

    doc.setFontSize(9);
    doc.setTextColor(92, 92, 102);
    y = addWrappedText(doc, `Why it matters: ${m.whyItMatters}`, PAGE_MARGIN, y, CONTENT_WIDTH, 5);
    y += 2;
    y = addWrappedText(doc, `What to ask for: ${m.whatToAskFor}`, PAGE_MARGIN, y, CONTENT_WIDTH, 5);
    y += 5;

    doc.setDrawColor(230, 220, 205);
    doc.line(PAGE_MARGIN, y, PAGE_MARGIN + CONTENT_WIDTH, y);
    y += 6;
  }

  // Clauses by risk level
  for (const level of RISK_LEVEL_ORDER) {
    const clauses = analysis.clauses.filter((c) => c.riskLevel === level);
    if (clauses.length === 0) continue;

    y = checkPageBreak(doc, y, 15);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...RISK_COLORS[level]);
    doc.text(`${RISK_LABEL[level]} Clauses (${clauses.length})`, PAGE_MARGIN, y);
    doc.setTextColor(14, 15, 22);
    y += 7;

    for (const clause of clauses) {
      y = renderClause(doc, clause, y);
    }
  }

  // Missing clauses
  if (analysis.missingClauses.length > 0) {
    y = checkPageBreak(doc, y, 15);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(14, 15, 22);
    doc.text("Missing Clauses", PAGE_MARGIN, y);
    y += 7;

    doc.setFontSize(10);
    for (const m of analysis.missingClauses) {
      y = checkPageBreak(doc, y, 15);
      doc.setFont("helvetica", "bold");
      doc.text(sanitizePdfText(m.title), PAGE_MARGIN, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(92, 92, 102);
      y = addWrappedText(
        doc,
        `Why it matters: ${m.whyItMatters}`,
        PAGE_MARGIN + 2,
        y,
        CONTENT_WIDTH - 2,
        5,
      );
      y += 2;
      y = addWrappedText(
        doc,
        `What to ask for: ${m.whatToAskFor}`,
        PAGE_MARGIN + 2,
        y,
        CONTENT_WIDTH - 2,
        5,
      );
      y += 4;
      doc.setTextColor(14, 15, 22);
    }
  }

  // Key dates
  if (analysis.keyDates.length > 0) {
    y = checkPageBreak(doc, y, 15);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(14, 15, 22);
    doc.text("Key Dates", PAGE_MARGIN, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const sorted = [...analysis.keyDates].sort((a, b) => {
      const order = { HIGH: 0, MEDIUM: 1, LOW: 2 };
      return order[a.urgency] - order[b.urgency];
    });
    for (const d of sorted) {
      y = checkPageBreak(doc, y, 8);
      doc.setTextColor(14, 15, 22);
      doc.text(
        sanitizePdfText(`${URGENCY_PREFIX[d.urgency]}${d.label}: ${d.value}`),
        PAGE_MARGIN + 2,
        y,
      );
      y += 5;
    }
    y += 3;
  }

  // Rights & Obligations
  const listSections: Array<[string, string[]]> = [
    ["Your Rights", analysis.yourRights],
    ["Your Obligations", analysis.yourObligations],
  ];
  for (const [heading, items] of listSections) {
    if (items.length === 0) continue;
    y = checkPageBreak(doc, y, 15);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(14, 15, 22);
    doc.text(heading, PAGE_MARGIN, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(92, 92, 102);
    for (const item of items) {
      y = checkPageBreak(doc, y, 8);
      y = addWrappedText(doc, `• ${item}`, PAGE_MARGIN + 2, y, CONTENT_WIDTH - 2, 5);
      y += 2;
    }
    y += 3;
  }

  // Add footers
  const totalPages = getNumberOfPages(doc);
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  return doc.output("blob");
}

export async function downloadPdf(analysis: AnalysisResult): Promise<void> {
  const blob = await toPdf(analysis);
  const date = new Date(analysis.analyzedAt).toISOString().slice(0, 10);
  const filename = `lexlight-analysis-${date}.pdf`;

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
