import type { AnalysisResult, ClauseAnalysis, RiskLevel } from "@/lib/types";
import { RISK_LEVEL_ORDER } from "@/lib/constants";
import { escapeMarkdown } from "@/lib/sanitize";

const RISK_LABEL: Record<RiskLevel, string> = {
  RED: "🔴 Red Flag",
  YELLOW: "🟡 Unusual",
  CONTEXT_DEPENDENT: "⚪ Context Dependent",
  GREEN: "🟢 Standard",
};

const URGENCY_LABEL = { HIGH: "🔴", MEDIUM: "🟡", LOW: "🟢" } as const;

function formatClause(c: ClauseAnalysis): string {
  const lines: string[] = [
    `### ${RISK_LABEL[c.riskLevel]}: ${escapeMarkdown(c.title)}`,
    `${escapeMarkdown(c.plainEnglish)}`,
    ``,
    `**Why it matters:** ${escapeMarkdown(c.riskReason)}`,
    `**Compared to standard:** ${escapeMarkdown(c.comparisonToStandard)}`,
    `**Your obligation:** ${escapeMarkdown(c.obligation)}`,
  ];
  if (c.contextNote) lines.push(`**Context note:** ${escapeMarkdown(c.contextNote)}`);
  if (c.negotiationTip) lines.push(`**Negotiation tip:** ${escapeMarkdown(c.negotiationTip)}`);
  if (c.affectedByMismatch) lines.push(`⚠️ *This clause is affected by a jurisdiction mismatch.*`);
  if (c.originalExcerpt) {
    lines.push(
      ``,
      `<details><summary>Original text</summary>`,
      ``,
      `\`\`\``,
      c.originalExcerpt,
      `\`\`\``,
      `</details>`,
    );
  }
  return lines.join("\n");
}

export function toMarkdown(analysis: AnalysisResult): string {
  const date = new Date(analysis.analyzedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const sections: string[] = [];

  // Header
  sections.push(
    `# LexLight Analysis Report`,
    ``,
    `**Document type:** ${analysis.documentType.replace(/_/g, " ")}`,
    `**Governing law:** ${analysis.governingLawJurisdiction ?? "Not specified"}`,
    `**Effective jurisdiction:** ${analysis.effectiveJurisdiction}`,
    `**Overall risk:** ${analysis.overallRiskLabel} (${analysis.overallRiskScore}/100)`,
    `**Analyzed:** ${date}`,
    ``,
    `---`,
  );

  // Jurisdiction mismatch
  if (analysis.jurisdictionMismatch) {
    const m = analysis.jurisdictionMismatch;
    sections.push(
      ``,
      `## ⚠️ Jurisdiction Mismatch (${m.confidence} confidence)`,
      ``,
      escapeMarkdown(m.plainEnglish),
      ``,
      `**Why it matters:** ${escapeMarkdown(m.whyItMatters)}`,
      `**What to ask for:** ${escapeMarkdown(m.whatToAskFor)}`,
      `**Clauses affected:** ${m.affectedClauseIds.join(", ") || "none"}`,
      ``,
      `---`,
    );
  }

  // Clause sections by risk level
  for (const level of RISK_LEVEL_ORDER) {
    const clauses = analysis.clauses.filter((c) => c.riskLevel === level);
    if (clauses.length === 0) continue;
    sections.push(``, `## ${RISK_LABEL[level]} Clauses (${clauses.length})`);
    for (const c of clauses) {
      sections.push(``, formatClause(c));
    }
    sections.push(``, `---`);
  }

  // Missing clauses
  if (analysis.missingClauses.length > 0) {
    sections.push(``, `## Missing Clauses`);
    for (const m of analysis.missingClauses) {
      sections.push(
        ``,
        `### ${escapeMarkdown(m.title)}`,
        `**Why it matters:** ${escapeMarkdown(m.whyItMatters)}`,
        `**What to ask for:** ${escapeMarkdown(m.whatToAskFor)}`,
      );
    }
    sections.push(``, `---`);
  }

  // Key dates
  if (analysis.keyDates.length > 0) {
    sections.push(``, `## Key Dates`);
    const sorted = [...analysis.keyDates].sort((a, b) => {
      const order = { HIGH: 0, MEDIUM: 1, LOW: 2 };
      return order[a.urgency] - order[b.urgency];
    });
    for (const d of sorted) {
      sections.push(
        `- ${URGENCY_LABEL[d.urgency]} **${escapeMarkdown(d.label)}:** ${escapeMarkdown(d.value)}`,
      );
    }
    sections.push(``, `---`);
  }

  // Rights
  if (analysis.yourRights.length > 0) {
    sections.push(``, `## Your Rights`);
    for (const r of analysis.yourRights) sections.push(`- ${escapeMarkdown(r)}`);
    sections.push(``, `---`);
  }

  // Obligations
  if (analysis.yourObligations.length > 0) {
    sections.push(``, `## Your Obligations`);
    for (const o of analysis.yourObligations) sections.push(`- ${escapeMarkdown(o)}`);
    sections.push(``, `---`);
  }

  // Footer
  sections.push(
    ``,
    `*Generated by [LexLight](https://lexlight.com) — This report is not legal advice. Consult a qualified attorney for guidance specific to your situation.*`,
  );

  return sections.join("\n");
}

export function downloadMarkdown(analysis: AnalysisResult): void {
  const content = toMarkdown(analysis);
  const date = new Date(analysis.analyzedAt).toISOString().slice(0, 10);
  const filename = `lexlight-analysis-${date}.md`;

  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();

  URL.revokeObjectURL(url);
}
