export interface JurisdictionOption {
  value: string;
  label: string;
}

export const US_STATES: JurisdictionOption[] = [
  { value: "US-AL", label: "Alabama, USA" },
  { value: "US-AK", label: "Alaska, USA" },
  { value: "US-AZ", label: "Arizona, USA" },
  { value: "US-AR", label: "Arkansas, USA" },
  { value: "US-CA", label: "California, USA" },
  { value: "US-CO", label: "Colorado, USA" },
  { value: "US-CT", label: "Connecticut, USA" },
  { value: "US-DE", label: "Delaware, USA" },
  { value: "US-FL", label: "Florida, USA" },
  { value: "US-GA", label: "Georgia, USA" },
  { value: "US-HI", label: "Hawaii, USA" },
  { value: "US-ID", label: "Idaho, USA" },
  { value: "US-IL", label: "Illinois, USA" },
  { value: "US-IN", label: "Indiana, USA" },
  { value: "US-IA", label: "Iowa, USA" },
  { value: "US-KS", label: "Kansas, USA" },
  { value: "US-KY", label: "Kentucky, USA" },
  { value: "US-LA", label: "Louisiana, USA" },
  { value: "US-ME", label: "Maine, USA" },
  { value: "US-MD", label: "Maryland, USA" },
  { value: "US-MA", label: "Massachusetts, USA" },
  { value: "US-MI", label: "Michigan, USA" },
  { value: "US-MN", label: "Minnesota, USA" },
  { value: "US-MS", label: "Mississippi, USA" },
  { value: "US-MO", label: "Missouri, USA" },
  { value: "US-MT", label: "Montana, USA" },
  { value: "US-NE", label: "Nebraska, USA" },
  { value: "US-NV", label: "Nevada, USA" },
  { value: "US-NH", label: "New Hampshire, USA" },
  { value: "US-NJ", label: "New Jersey, USA" },
  { value: "US-NM", label: "New Mexico, USA" },
  { value: "US-NY", label: "New York, USA" },
  { value: "US-NC", label: "North Carolina, USA" },
  { value: "US-ND", label: "North Dakota, USA" },
  { value: "US-OH", label: "Ohio, USA" },
  { value: "US-OK", label: "Oklahoma, USA" },
  { value: "US-OR", label: "Oregon, USA" },
  { value: "US-PA", label: "Pennsylvania, USA" },
  { value: "US-RI", label: "Rhode Island, USA" },
  { value: "US-SC", label: "South Carolina, USA" },
  { value: "US-SD", label: "South Dakota, USA" },
  { value: "US-TN", label: "Tennessee, USA" },
  { value: "US-TX", label: "Texas, USA" },
  { value: "US-UT", label: "Utah, USA" },
  { value: "US-VT", label: "Vermont, USA" },
  { value: "US-VA", label: "Virginia, USA" },
  { value: "US-WA", label: "Washington, USA" },
  { value: "US-WV", label: "West Virginia, USA" },
  { value: "US-WI", label: "Wisconsin, USA" },
  { value: "US-WY", label: "Wyoming, USA" },
  { value: "US-DC", label: "District of Columbia, USA" },
];

export const COMMON_COUNTRIES: JurisdictionOption[] = [
  { value: "GB", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "IN", label: "India" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "JP", label: "Japan" },
  { value: "SG", label: "Singapore" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "IE", label: "Ireland" },
  { value: "NL", label: "Netherlands" },
  { value: "CH", label: "Switzerland" },
];

export const ALL_JURISDICTIONS: JurisdictionOption[] = [
  { value: "", label: "Not specified" },
  ...US_STATES,
  ...COMMON_COUNTRIES,
];
